In [9]:
import pandas as pd
import pickle

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

,age,sex,bmi,children,smoker,charges
0,19,female,27.900,0,yes,16884.92400
1,18,male,33.770,1,no,1725.55230
2,28,male,33.000,3,no,4449.46200
3,33,male,22.705,0,no,21984.47061
4,32,male,28.880,0,no,3866.85520
...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830
1334,18,female,31.920,0,no,2205.98080
1335,18,female,36.850,0,no,1629.83350
1336,21,female,25.800,0,no,2007.94500


In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']


In [5]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)


In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
scy = StandardScaler()
y_train = scy.fit_transform(y_train.values.reshape(-1, 1))
y_test = scy.transform(y_test.values.reshape(-1, 1))



In [7]:
preinput = sc.transform([[22,19,1,0,1]])
preinput

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.25366777, -1.88849237, -0.0755796 , -0.98885138,  2.00280702]])

In [10]:
loaded_model=pickle.load(open("insurance_pre.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([0.56820841])

In [11]:
preoutput = scy.inverse_transform([result])
preoutput

array([[19851.70533422]])