In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

,age,sex,bmi,children,smoker,charges
0,19,female,27.900,0,yes,16884.92400
1,18,male,33.770,1,no,1725.55230
2,28,male,33.000,3,no,4449.46200
3,33,male,22.705,0,no,21984.47061
4,32,male,28.880,0,no,3866.85520
...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830
1334,18,female,31.920,0,no,2205.98080
1335,18,female,36.850,0,no,1629.83350
1336,21,female,25.800,0,no,2007.94500


In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset

,age,bmi,children,charges,sex_male,smoker_yes
0,19,27.900,0,16884.92400,False,True
1,18,33.770,1,1725.55230,True,False
2,28,33.000,3,4449.46200,True,False
3,33,22.705,0,21984.47061,True,False
4,32,28.880,0,3866.85520,True,False
...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False
1334,18,31.920,0,2205.98080,False,False
1335,18,36.850,0,1629.83350,False,False
1336,21,25.800,0,2007.94500,False,False


In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
scy = StandardScaler()

X_train


array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

 Reshape before scaling 
The reason to reshape y_train and y_test into 2D arrays before scaling is because of how scikit-learn’s StandardScaler is designed:

StandardScaler expects input in the form of a 2D array with shape (n_samples, n_features).
 target variable (y_train, y_test) is a 1D Series (shape (n_samples,)).
When I pass a 1D array directly, StandardScaler doesn’t know if I mean:
multiple samples with one feature each, or one sample with multiple features.
To avoid ambiguity, scikit-learn enforces the requirement that the input must be explicitly 2D.


The difference comes down to how scikit-learn interprets the shape of your data:

X_train and X_test are already 2D arrays (shape (n_samples, n_features)), because you selected multiple columns ([['age', 'bmi', 'children','sex_male', 'smoker_yes']]).
Example: if you have 1000 rows and 5 features, the shape is (1000, 5). That’s exactly what StandardScaler expects.

y_train and y_test, on the other hand, are 1D Series (shape (n_samples,)).
Example: (1000,) — just one column of values. StandardScaler doesn’t accept this directly, because it requires a 2D input where each column is treated as a separate feature.

So:

X_train → fine, already 2D.

y_train → needs reshaping into (n_samples, 1) so that StandardScaler knows it’s feature column."""

In [8]:


#.reshape(-1, 1) converts your 1D array into a 2D array with one column (one feature).one -1 tells NumPy to infer the number of rows automatically.

y_train = scy.fit_transform(y_train.values.reshape(-1, 1))
y_test = scy.transform(y_test.values.reshape(-1, 1))
y_train


array([[-9.74704706e-01],
       [ 2.43595227e+00],
       [-3.54990167e-01],
       [-7.40302357e-01],
       [-7.72992119e-01],
       [-3.56105745e-01],
       [-3.12405716e-01],
       [-4.57593414e-01],
       [-1.32221217e-01],
       [-7.93946645e-01],
       [-9.29662595e-01],
       [-8.53316663e-01],
       [-7.77169102e-01],
       [-4.74957055e-01],
       [ 1.80292292e+00],
       [-1.77344443e-02],
       [-5.06614701e-01],
       [ 1.10861258e+00],
       [-1.18018584e-01],
       [-9.62233850e-01],
       [-1.95774021e-01],
       [-1.98220356e-01],
       [-7.48375214e-01],
       [-9.73871211e-01],
       [ 2.62922835e+00],
       [-4.66763102e-01],
       [ 1.28665821e+00],
       [-8.07799710e-01],
       [ 9.62739634e-01],
       [-6.47487283e-01],
       [-1.09681055e-01],
       [ 3.90197468e-01],
       [ 1.75728577e+00],
       [-3.02271094e-01],
       [-4.33454326e-01],
       [-9.67185594e-01],
       [-7.53146992e-01],
       [-4.09292284e-01],
       [-9.3

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']} 



grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 



Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_

grid_prediction = grid.predict(X_test)

from sklearn.metrics import r2_score
r_score = r2_score(y_test,grid_prediction)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)



The R_score value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.8818140952905176


In [12]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.102039,0.007152,0.010308,0.000938,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",8.164633e-01,8.040041e-01,8.640516e-01,8.322548e-01,7.450273e-01,8.123602e-01,3.921270e-02,1
1,0.353507,0.078008,0.004274,0.000200,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",8.041773e-01,7.850967e-01,8.602267e-01,8.174638e-01,7.609121e-01,8.055753e-01,3.329936e-02,4
2,0.067381,0.002834,0.013830,0.006560,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.119323e+03,-4.458988e+03,-3.041481e+03,-3.533611e+03,-2.743267e+03,-3.379334e+03,5.959506e+02,32
3,0.350189,0.036651,0.004618,0.000197,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",6.540292e-01,6.209861e-01,6.330632e-01,6.033335e-01,5.969204e-01,6.216665e-01,2.062114e-02,21
4,0.119841,0.023362,0.012116,0.000737,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",8.165165e-01,8.037780e-01,8.639829e-01,8.322501e-01,7.450087e-01,8.123072e-01,3.921136e-02,2
5,0.442488,0.093103,0.004225,0.000116,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",8.041550e-01,7.854628e-01,8.602929e-01,8.177500e-01,7.609739e-01,8.057269e-01,3.328044e-02,3
6,0.067734,0.002983,0.012227,0.000442,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-2.106276e+03,-3.752820e+03,-3.119519e+03,-3.532598e+03,-2.657935e+03,-3.033830e+03,5.957704e+02,31
7,0.337934,0.020498,0.004520,0.000125,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",6.540292e-01,6.209861e-01,6.330632e-01,6.033335e-01,5.969204e-01,6.216665e-01,2.062114e-02,21
8,0.465714,0.041521,0.012078,0.000385,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",7.945466e-01,7.129582e-01,8.082692e-01,8.007991e-01,6.925698e-01,7.618286e-01,4.884873e-02,13
9,3.685128,1.097217,0.004318,0.000152,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",8.041580e-01,7.830147e-01,8.597524e-01,8.158259e-01,7.609834e-01,8.047469e-01,3.327530e-02,7


In [13]:
import pickle
filename="insurance_pre.sav"
pickle.dump(grid,open(filename,'wb'))

In [14]:
preinput = sc.transform([[25,19,1,0,1]])
preinput

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.03919296, -1.88849237, -0.0755796 , -0.98885138,  2.00280702]])

In [15]:
loaded_model=pickle.load(open("insurance_pre.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([0.60743072])

In [19]:
preoutput = scy.inverse_transform([result])
preoutput



array([[20315.11685188]])